name: KitGUI
api: 3.9.0
main: KITGUI\Main
version: 1.0
author: ethaniccc

commands:
 kits:
  description: Opens the KitGUI
 viewkit:
  description: View contents inside of a kit using a GUI
 guiinfo:
  description: Plugin credits + more!
 xyz:
  description: Get your XYZ
